### ISSUE TITLE
Video segmentation workflow issue

### ISSUE THREAD

**Issue by david-rokeby** [kijai/ComfyUI-segment-anything-2#23]
I have attempted to reconstruct the video segmentation example in the top movie in the github movie.

I am working on Ubuntu 22.04, with Pytorch 2.4, cuda 12.4. Single image segmentation seems to work, but if I switch to video segmentation, I get:

Error occurred when executing Sam2Segmentation:

'SAM2VideoPredictor' object has no attribute 'set_image'

  File "/home/bmolab/Projects/pytorch/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/bmolab/Projects/pytorch/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/bmolab/Projects/pytorch/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/bmolab/Projects/pytorch/ComfyUI/custom_nodes/ComfyUI-segment-anything-2/nodes.py", line 226, in segment
    model.set_image(image_np)
  File "/home/bmolab/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")

**Comment by kijai** [comment]
Are you possible feeding it just a single image? That would trigger this error.
